{"uuid": "dc12a1bb-06fb-47e4-bd4d-b89117cb7772", "children": ["565e9995-1cb8-4934-b72f-dd53fe8a914e"], "befores": [{"name": "shell", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'datetime.datetime' has no attribute 'datetime'\n", "trace": "  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PyTest-Automation-Framework-master\\tests\\conftest.py\", line 71, in shell\n    currentDT = datetime.datetime.now()\n"}, "start": 1688485685675, "stop": 1688485695685}], "start": 1688485685675, "stop": 1688485695716}