{"name": "Power bi comparison with sql", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'get_screenshot_as_file'", "trace": "@pytest.fixture(scope=\"session\")\n    def shell():  # pylint: disable=redefined-outer-name\n    \n        shell = OpenPowerBIPage({\n            \"temp\": TARGET_DIR,\n            \"headless\": \"false\"\n    \n        })\n        try:\n>           shell.power_BI_login(emailID, decode(encryptedPasscode))\n\ntests\\conftest.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <src.pom.pages.openpowerbi_page.OpenPowerBIPage object at 0x0000029EF0440760>, emailID = 'vaishnavi.gopala@tigeranalytics.com', password = 'Tiger#6789'\n\n    def power_BI_login(self, emailID, password):\n        time.sleep(10)\n>       if len(self.find_elements_by_xpath(self.emailID))>0:\n\nsrc\\pom\\pages\\openpowerbi_page.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <src.pom.pages.openpowerbi_page.OpenPowerBIPage object at 0x0000029EF0440760>, locator = '//*[@name=\"loginfmt\"]'\n\n    def find_elements_by_xpath(self, locator):\n>       return self.driver.find_elements('xpath', locator)\nE       AttributeError: 'dict' object has no attribute 'find_elements'\n\nsrc\\pom\\pages\\base_page.py:26: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\n    @pytest.fixture(scope=\"session\")\n    def shell():  # pylint: disable=redefined-outer-name\n    \n        shell = OpenPowerBIPage({\n            \"temp\": TARGET_DIR,\n            \"headless\": \"false\"\n    \n        })\n        try:\n            shell.power_BI_login(emailID, decode(encryptedPasscode))\n            yield shell\n        except Exception as e:\n            currentDT = datetime.datetime.now()\n>           shell.driver.get_screenshot_as_file(\n                os.path.join(SCREENSHOTS_DIR, \"connect_fail_{}.png\".format(str(currentDT).replace(\" \", \"_\")))\n            )\nE           AttributeError: 'dict' object has no attribute 'get_screenshot_as_file'\n\ntests\\conftest.py:73: AttributeError"}, "start": 1688486183769, "stop": 1688486183769, "uuid": "7c321755-f3ce-49e2-9ac7-9679facea9a3", "historyId": "b0336c530c443842ce6471649281d16f", "testCaseId": "52ed46f92fc8742b817ccd38918a09bf", "fullName": "tests.test_openPowerBI.TestPowerBIReport#test_report", "labels": [{"name": "tag", "value": "smoke"}, {"name": "tag", "value": "@pytest.mark.usefixtures('get_driver')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_openPowerBI"}, {"name": "subSuite", "value": "TestPowerBIReport"}, {"name": "host", "value": "TIGER03699"}, {"name": "thread", "value": "18748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_openPowerBI"}]}