{"uuid": "7e50503e-ea81-4dfa-84e7-f9e0726f4552", "children": ["fef35a83-beff-49a6-b0db-004cd4824541"], "befores": [{"name": "on_failure", "status": "passed", "start": 1688716394246, "stop": 1688716394246}], "afters": [{"name": "on_failure::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54449): Max retries exceeded with url: /session/b95d766f3c721df9fc7764b56ac5727b/timeouts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029178E85DE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 916, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\PyTest-Automation-Framework-master\\tests\\conftest.py\", line 139, in on_failure\n    driver.implicitly_wait(10)\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 769, in implicitly_wait\n    self.execute(Command.SET_TIMEOUTS, {\"implicit\": int(float(time_to_wait) * 1000)})\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\vaishnavi.gopala\\PycharmProjects\\MarsInstaShop\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1688716547614, "stop": 1688716563834}], "start": 1688716394246, "stop": 1688716563834}